### ISSUE TITLE
Make file description of main executlabe configurable

### ISSUE THREAD

**Issue by sebkur** [mobanisto/pinpit-gradle-plugin#20]
The file description can show up in dialogs such as this one:

![Firewall](https://user-images.githubusercontent.com/1633488/212265531-85cb6946-122f-43a7-932b-a214581ef993.png)

According to https://learn.microsoft.com/en-us/windows/win32/menurc/versioninfo-resource:

FileDescription | File description to be presented to users. This string may be displayed in a list box when the user is choosing files to install—for example, Keyboard Driver for AT-Style Keyboards. This string is required.
-- | --

Currently, we're setting this to the packageDescription which might not be a good fit to describe the app as a whole with out the packageName visible. Instead of merging the two automatically, the user should be able to set a separate string.

**Comment by ialokim** [comment]
Fixed via 87137603740758b4fec20b4783744e855122c099, I'd guess?

**Comment by sebkur** [comment]
Indeed 👍
