### ISSUE TITLE
Modfify Windows launcher with icon (rebrand)

### ISSUE THREAD

**Issue by sebkur** [mobanisto/pinpit-gradle-plugin#6]
See https://github.com/openjdk/jdk/blob/master/src/jdk.jpackage/windows/classes/jdk/jpackage/internal/ExecutableRebrander.java for what's happening when packaging using JPackage.

**Comment by sebkur** [comment]
In particular there's some native code executed with source in [IconSwap.cpp](https://github.com/openjdk/jdk/blob/master/src/jdk.jpackage/windows/native/libjpackage/IconSwap.cpp#L99).

Maybe we can compile this to a standalone .exe program and execute that using wine on Linux and natively on Windows.

**Comment by sebkur** [comment]
It would probably be even better to use a library such as https://github.com/imcdonagh/image4j for reading the ICO files and then manipulating the EXE cross-platform in Java code. However, I'm not sure how much secret sauce is contained in the [`UpdateResource()`](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-updateresourcew) library call that the native code seems to do in order to put the icon into the exe.

**Comment by sebnuc** [comment]
This concerns:
* the icon associated with the exe (i.e. the way the exe appears in Windows explorer etc.), not the icon of the application as in how it appears in the taskbar the window switcher (that can be set within the application)
* the properties visible in the exe properties dialog, i.e. compare this, left hand side is an unbranded exe, right hand side is the branded Briar exe:

![pinpit-exe-properties](https://user-images.githubusercontent.com/113822008/204508656-3c79234a-156d-4676-a5c5-9e26337da9ca.png)

**Comment by sebnuc** [comment]
In `ExecutableRebrander` we have [`rebrandExecutable()`](https://github.com/openjdk/jdk/blob/master/src/jdk.jpackage/windows/classes/jdk/jpackage/internal/ExecutableRebrander.java#L96) which uses [WinInstaller.template](https://github.com/openjdk/jdk/blob/master/src/jdk.jpackage/windows/classes/jdk/jpackage/internal/resources/WinInstaller.template) to update resources in the exe using `UpdateResource()`. It is defined like this with the uppercase placeholders being replaced:

```
FIXEDFILEINFO_FileVersion=FIXEDFILEINFO_FILE_VERSION
FIXEDFILEINFO_ProductVersion=FIXEDFILEINFO_FILE_VERSION
CompanyName=COMPANY_NAME
FileDescription=Installer of FILE_DESCRIPTION
FileVersion=FILE_VERSION
InternalName=INTERNAL_NAME
LegalCopyright=LEGAL_COPYRIGHT
OriginalFilename=ORIGINAL_FILENAME
ProductName=PRODUCT_NAME Installer
ProductVersion=FILE_VERSION
```

**Comment by sebkur** [comment]
Instead of building our own executable, this could work: https://github.com/electron/rcedit

**Comment by sebkur** [comment]
Implemented via https://github.com/mobanisto/pe-rebrander in fb4566ca729d1e65035447ef9ba43a9140f82aa1
